Algoritmo "Modulo"

Var

x,r : real
a,b : inteiro
m : Inteiro
Inicio

   Escreval("digite modulo ")
   Leia(m)

   Escreval("digite x ")
   Leia(x)

   r := (X % m)
   SE r=0 ENTAO
      ESCREVAL("MULTIPLO",r)
   SENAO
      ESCREVAL("N/ MULTIPLO",r)
   FIMSE

   Escreval("digite A ")
   Leia(a)
   b := (a % m)
   SE b=0 ENTAO
      ESCREVAL("MULTIPLO",b)
   SENAO
      ESCREVAL("N/ MULTIPLO",b)
   FIMSE

Fimalgoritmo
FIMSE